- name: 创建TLS临时目录
  file:
    path: "{{tmp_tls_dir}}"
    state: directory

- name: 创建 ca-config.json
  template:
    src: ca-config.json.j2
    dest: "{{tmp_tls_dir}}/ca-config.json"

- name: 创建 ca-config.json
  template:
    src: ca-csr.json.j2
    dest: "{{tmp_tls_dir}}/ca-csr.json"

- name: 生成ca证书
  shell: "{{bin_dir}}/cfssl gencert -initca ca-csr.json | {{bin_dir}}/cfssljson -bare ca"
  args:
    chdir: "{{tmp_tls_dir}}"