- name: 复制kubernetes master执行文件
  become: true
  copy:
    src: "{{tmp_bin_dir}}/{{item}}"
    dest: "{{bin_dir}}"
    mode: 0755
  with_items:
  - "{{bin_files.kubernetes_master}}"

- name: 生成 token.csv
  become: true
  template:
    src: token.csv.j2
    dest: "{{cert_kubernetes_dir}}/token.csv"

- name: 生成 basic-auth.csv
  become: true
  template:
    src: basic-auth.csv.j2
    dest: "{{cert_kubernetes_dir}}/basic-auth.csv"

- name: 生成 kubernetes master 相关服务
  become: true
  template:
    src: "{{item}}.j2"
    dest: "/etc/systemd/system/{{item}}"
  with_items:
  - kube-apiserver.service
  - kube-controller-manager.service
  - kube-scheduler.service