- name: 获取 ingress-nginx 定义文件
  copy:
    src: "{{playbook_dir}}/../kubernetes/ingress"
    dest: "{{tmp_dir}}/kubernetes"

- name: "{{op}} ingress-nginx"
  become: true
  shell: "{{bin_dir}}/kubectl {{op}} -f {{tmp_dir}}/kubernetes/ingress/ingress-nginx/{{item}}"
  with_items:
  - ingress-nginx-namespace.yaml
  - default-backend.yaml
  - nginx-configmap.yaml
  - ingress-nginx-controller.yaml
  - ingress-nginx-rbac.yaml
  - tcp-services-configmap.yaml
  - udp-services-configmap.yaml