- name: 复制docker执行文件
  become: true
  copy:
    src: "{{tmp_bin_dir}}/{{item}}"
    dest: "{{bin_dir}}"
    mode: 0755
  with_items:
  - "{{bin_files.docker}}"

- name: 生成docker服务
  become: true
  template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service