- name: 安装cfssl cfssljson cfssl-certinfo
  become: true
  copy:
    src: "{{res_dir}}/{{item}}_linux-amd64"
    dest: "{{bin_dir}}/{{item}}"
    mode: 0755
  with_items:
  - cfssl
  - cfssljson
  - cfssl-certinfo