- name: 创建 etcd 数据目录
  become: true
  file:
    path: /var/lib/etcd
    state: directory

- name: 复制 etcd 执行文件
  become: true
  copy:
    src: "{{tmp_bin_dir}}/{{item}}"
    dest: "{{bin_dir}}"
    mode: 0755
  with_items:
  - "{{bin_files.etcd}}"

- name: 生成 etcd 服务
  become: true
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service