- name: 复制flannel执行文件
  become: true
  copy:
    src: "{{tmp_bin_dir}}/{{item}}"
    dest: "{{bin_dir}}"
    mode: 0755
  with_items:
  - "{{bin_files.flannel}}"

- name: 生成flannel服务
  become: true
  template:
    src: flanneld.service.j2
    dest: /etc/systemd/system/flanneld.service

- name: 设置docker网段
  become: true
  shell: "/usr/local/bin/etcdctl \
          --ca-file=/etc/kubernetes/ssl/ca.pem \
          --cert-file=/etc/flanneld/ssl/flanneld.pem \
          --key-file=/etc/flanneld/ssl/flanneld-key.pem \
          set /kubernetes/network/config \"{ \"Network\": \"{{docker_ip_range}}\" }\""