- name: 复制kubernetes client执行文件
  become: true
  copy:
    src: "{{tmp_bin_dir}}/{{item}}"
    dest: "{{bin_dir}}"
    mode: 0755
  with_items:
  - "{{bin_files.kubernetes_client}}"

- name: 设置kubernetes client
  shell: "{{item}}"
  with_items:
  - "{{bin_dir}}/kubectl config set-cluster kubernetes \
       --certificate-authority=/etc/kubernetes/ssl/ca.pem \
       --embed-certs=true \
       --server=https://{{master_ip}}:6443"

  - "{{bin_dir}}/kubectl config set-credentials admin \
       --client-certificate=/etc/kubernetes/ssl/admin.pem \
       --embed-certs=true \
       --client-key=/etc/kubernetes/ssl/admin-key.pem"

  - "{{bin_dir}}/kubectl config set-context kubernetes \
       --cluster=kubernetes \
       --user=admin"

  - "{{bin_dir}}/kubectl config use-context kubernetes"