- name: 检测kubernetes master服务文件是否存在
  stat:
    path: "/etc/systemd/system/{{item}}.service"
  register: file
  with_items:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler

- name: 停止kubernetes master服务
  become: true
  systemd:
    state: stopped
    enabled: no
    name: "{{item.item}}" # item.item为服务文件名称，也就是上一个任务的item
  with_items:
  - "{{file.results}}"
  when: item.stat.exists == true

- name: 删除kubernetes master相关服务文件
  become: true
  file:
    path: "/etc/systemd/system/{{item}}.service"
    state: absent
  with_items:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler

- name: 删除kubernetes master执行文件
  become: true
  file:
    path: "{{bin_dir}}/{{item}}"
    state: absent
  with_items:
  - "{{bin_files.kubernetes_master}}"

- name: 删除 token.csv、basic-auth.csv
  become: true
  file:
    path: "{{cert_kubernetes_dir}}/{{item}}"
    state: directory
  with_items:
  - token.csv
  - basic-auth.csv
