nodes:
- {name: "node-1",ip: "192.168.100.101"}
- {name: "node-2",ip: "192.168.100.102"}
- {name: "node-3",ip: "192.168.100.103"}

cluster_svc_ip: 168.168.0.1

service_node_port_range: 8400-9000

service_cluster_ip_range: 168.168.0.0/16

cluster_cidr: 10.0.0.0/16

cluster_dns: 168.168.0.100

cluster_domain: cluster.local.

master_ip: "{{nodes[0].ip}}"

bootstrap_token: 41f7e4ba8b7be874fcff18bf5cf41a7c

iface: enp0s8

node_ip: "{{ansible_enp0s8.ipv4.address}}"

etcd_nodes: "{%for n in nodes %}etcd_{{n.name}}=https://{{n.ip}}:2380{% if not loop.last %},{% endif %}{% endfor %}"

etcd_endpoints: "{%for n in nodes %}https://{{n.ip}}:2379{% if not loop.last %},{% endif %}{% endfor %}"

flannel_etcd_prefix: /kubernetes/network

bin_dir: /usr/local/bin
base_dir: "/home/ifnoelse"
res_dir: "{{base_dir}}/res"
tmp_dir: "{{base_dir}}/tmp"
tmp_unzip_dir: "{{tmp_dir}}/unzip"
tmp_bin_dir: "{{tmp_dir}}/bin"
tmp_tls_dir: "{{tmp_dir}}/tls"

kubernetes_conf_dir: /etc/kubernetes
cert_etcd_dir: /etc/etcd/ssl
cert_flanneld_dir: /etc/flanneld/ssl
cert_kubernetes_dir: /etc/kubernetes/ssl
cert_ca_dir: /etc/kubernetes/ssl

cert_dirs:
- "{{cert_etcd_dir}}"
- "{{cert_flanneld_dir}}"
- "{{cert_kubernetes_dir}}"
- "{{cert_ca_dir}}"

bin_files:
  docker:
  - docker
  - docker-containerd
  - docker-containerd-ctr
  - docker-containerd-shim
  - dockerd
  - docker-init
  - docker-proxy
  - docker-runc
  etcd:
  - etcd
  - etcdctl
  flannel:
  - flanneld
  - mk-docker-opts.sh
  kubernetes_master:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  kubernetes_node:
  - kube-proxy
  - kubelet
  - kubectl
  kubernetes_client:
  - kubectl