nodes:
- {name: "node-1",ip: "192.168.100.101"}
- {name: "node-2",ip: "192.168.100.102"}
- {name: "node-3",ip: "192.168.100.103"}

cluster_svc_ip: 168.168.0.1

master_ip: "{{nodes[0].ip}}"

node_ip: "{{ansible_enp0s8.ipv4.address}}"

etcd_nodes: "{%for n in nodes %}etcd_{{n.name}}=https://{{n.ip}}:2380{% if not loop.last %},{% endif %}{% endfor %}"

bin_dir: /usr/local/bin
base_dir: "/home/ifnoelse"
res_dir: "{{base_dir}}/res"
tmp_dir: "{{base_dir}}/tmp"
tmp_unzip_dir: "{{tmp_dir}}/unzip"
tmp_bin_dir: "{{tmp_dir}}/bin"
tmp_tls_dir: "{{tmp_dir}}/tls"

etcd_tls_dir: /etc/etcd/ssl
flanneld_tls_dir: /etc/flanneld/ssl
kubernetes_tls_dir: /etc/kubernetes/ssl

bin_files:
  docker:
  - docker
  - docker-containerd
  - docker-containerd-ctr
  - docker-containerd-shim
  - dockerd
  - docker-init
  - docker-proxy
  - docker-runc
  etcd:
  - etcd
  - etcdctl
  flannel:
  - flanneld
  - mk-docker-opts.sh
  k8s_master:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - kubectl
  k8s_node:
  - kube-proxy
  - kubelet