- name: 创建证书相关目录
  become: true
  file:
    path: "{{item}}"
    state: directory
  with_items:
  - "{{etcd_cert_dir}}"
  - "{{kubernetes_cert_dir}}"
  - "{{flanneld_cert_dir}}"

- name: 分发ca证书
  become: true
  copy:
    src: "{{tmp_tls_dir}}/{{item}}"
    dest: "{{kubernetes_cert_dir}}"
    remote_src: yes
  with_items:
  - ca-key.pem
  - ca.pem

- name: 分发kubernetes证书
  become: true
  copy:
    src: "{{tmp_tls_dir}}/{{item}}"
    dest: "{{kubernetes_cert_dir}}/{{item}}"
  with_items:
  - kubernetes-key.pem
  - kubernetes.pem

- name: 分发flanneld证书
  become: true
  copy:
    src: "{{tmp_tls_dir}}/{{item}}"
    dest: "{{flanneld_cert_dir}}/{{item}}"
  with_items:
  - flanneld-key.pem
  - flanneld.pem

- name: 分发etcd证书
  become: true
  copy:
    src: "{{tmp_tls_dir}}/{{item}}"
    remote_src: yes
    dest: "{{etcd_cert_dir}}//{{item}}"
  with_items:
  - etcd-key.pem
  - etcd.pem