apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-svc
  namespace: ingress-nginx
  labels:
    k8s-app: ingress-nginx-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 8880
  - name: https
    port: 8843
    targetPort: 443
    nodePort: 8843
  selector:
    app: ingress-nginx