- name: 创建TLS临时目录
  file:
    path: "{{tmp_tls_dir}}"
    state: directory

- name: 创建 etcd-csr.json
  template:
    src: etcd-csr.json.j2
    dest: "{{tmp_tls_dir}}/etcd-csr.json"

- name: 生成etcd证书
  shell: "cfssl gencert -ca={{tmp_tls_dir}}/ca.pem \
                     -ca-key={{tmp_tls_dir}}/ca-key.pem \
                     -config={{tmp_tls_dir}}/ca-config.json \
                     -profile=kubernetes etcd-csr.json | cfssljson -bare etcd"
  args:
    chdir: "{{tmp_tls_dir}}"