- name: 安装cfssl工具
  include_tasks: cfssl.yaml
  tags:
  - install_cfssl

- name: 生成ca证书
  include_tasks: ca.yaml
  tags:
  - tls_ca

- name: 生成etcd证书
  include_tasks: etcd.yaml
  tags:
  - tls_etcd

- name: 生成admin证书
  include_tasks: admin.yaml
  tags:
  - tls_admin