- name: 安装 cfssl
  become: true
  copy:
    src: "{{res_dir}}/cfssl_linux-amd64"
    dest: "{{bin_dir}}/cfssl"
    owner: root
    group: root
    mode: 0755

- name: 创建TLS临时目录
  file:
    path: "{{tmp_tls_dir}}"
    state: directory

- name: 复制文件测试
- template:
    src: ca-config.json.j2
    dest: /etc/file.conf