#  gather_facts: no

#- name: "资源准备任务"
#  hosts: deploy
#  roles:
#  - prepare_res
#  tags:
#  - prepare_res

- name: "ca证书"
  hosts: deploy
  roles:
  - ca_cert
  tags:
  - ca_cert

- name: "etcd证书"
  hosts: etcd
  roles:
  - etcd_cert
  tags:
  - etcd_cert

- name: "安装etcd"
  hosts: all
  roles:
  - { role: install_etcd }
  - { role: service, cmd: "etcd_start" }
  tags:
  - install_etcd

#- name: "生成证书"
#  hosts: all
#  roles:
#  - gen_certificate
#  tags:
#  - gen_certificate
#
#- name: "分发证书"
#  hosts: all
#  roles:
#  - dist_certificate
#  tags:
#  - dist_certificate
#
#- name: "安装etcd"
#  hosts: all
#  roles:
#  - install_etcd
#  tags:
#  - install_etcd