#  gather_facts: no

#- name: "资源准备任务"
#  hosts: deploy
#  roles:
#  - prepare_res
#  tags:
#  - prepare_res

- name: "ca证书"
  hosts: deploy
  roles:
  - ca_cert
  tags:
  - ca_cert

- name: "etcd证书"
  hosts: all
  roles:
  - etcd_cert
  tags:
  - etcd_cert

- name: "flannel证书"
  hosts: all
  roles:
  - flannel_cert
  tags:
  - flannel_cert

- name: "安装etcd"
  hosts: all
  roles:
  - { role: install_etcd }
  - { role: service, s: "etcd", c: "start" }
  tags:
  - install_etcd

- name: "安装docker"
  hosts: all
  roles:
  - { role: install_docker }
  tags:
  - install_docker

- name: "安装flannel"
  hosts: all
  roles:
  - { role: install_flannel }
  tags:
  - install_flannel

#- name: "生成证书"
#  hosts: all
#  roles:
#  - gen_certificate
#  tags:
#  - gen_certificate
#
#- name: "分发证书"
#  hosts: all
#  roles:
#  - dist_certificate
#  tags:
#  - dist_certificate
#
#- name: "安装etcd"
#  hosts: all
#  roles:
#  - install_etcd
#  tags:
#  - install_etcd