- name: "资源准备任务"
  hosts: deploy
  gather_facts: no
  roles:
  - prepare_res
  tags:
  - prepare_res

- name: "生成证书"
  hosts: deploy
  gather_facts: no
  roles:
  - gen_certificate
  tags:
  - gen_certificate

- name: "分发证书"
  hosts: all
  gather_facts: no
  roles:
  - dist_certificate
  tags:
  - dist_certificate