# gather_facts: no

- name: "资源准备任务"
  hosts: deploy
  roles:
  - prepare_res
  tags:
  - prepare_res

- name: "ca证书"
  hosts: deploy
  roles:
  - cert_ca
  tags:
  - cert_ca

- name: "etcd证书"
  hosts: all
  roles:
  - cert_etcd
  tags:
  - cert_etcd

#- name: "etcd证书"
#  hosts: all
#  roles:
#  - { role: cert, csr_file: "etcd-csr.json", cert_dir: "{{cert_etcd_dir}}",cert_name: "etcd" }
#  tags:
#  - cert_etcd

- name: "admin证书"
  hosts: client
  roles:
  - cert_admin
  tags:
  - cert_admin

- name: "flannel证书"
  hosts: all
  roles:
  - cert_flannel
  tags:
  - cert_flannel

- name: "kubernetes master证书"
  hosts: all
  roles:
  - cert_kubernetes_master
  tags:
  - cert_kubernetes_master

- name: "安装etcd"
  hosts: all
  roles:
  - { role: install_etcd }
  - { role: service, s: "etcd", c: "start" }
  tags:
  - install_etcd

- name: "安装flannel"
  hosts: all
  roles:
  - { role: install_flannel }
  - { role: service, s: "flanneld", c: "start" }
  tags:
  - install_flannel

- name: "安装docker"
  hosts: all
  roles:
  - { role: install_docker }
  - { role: service, s: "docker", c: "start" }
  tags:
  - install_docker

- name: "安装kubernetes master"
  hosts: master
  roles:
  - { role: install_kubernetes_master }
  - { role: service, s: "kube-apiserver", c: "start" }
  - { role: service, s: "kube-controller-manager", c: "start" }
  - { role: service, s: "kube-scheduler", c: "start" }
  tags:
  - install_kubernetes_master

- name: "安装kubernetes client"
  hosts: client
  roles:
  - { role: install_kubernetes_client }
  tags:
  - install_kubernetes_client