- name: "删除res临时目录"
  gather_facts: no
  hosts: all
  roles:
  - del_res_tmp
  tags:
  - del_res_tmp

- name: "删除cfssl相关工具"
  gather_facts: no
  hosts: all
  roles:
  - del_cfssl
  tags:
  - del_cfssl

- name: "删除证书"
  gather_facts: no
  hosts: all
  roles:
  - del_cert
  tags:
  - del_cert

- name: "卸载docker"
  gather_facts: no
  hosts: node
  roles:
  - del_docker
  tags:
  - del_docker

- name: "卸载flannel"
  gather_facts: no
  hosts: node
  roles:
  - del_flannel
  tags:
  - del_flannel

- name: "卸载etcd"
  gather_facts: no
  hosts: etcd
  roles:
  - del_etcd
  tags:
  - del_etcd

- name: "卸载kubernetes master"
  gather_facts: no
  hosts: master
  roles:
  - del_kubernetes_master
  tags:
  - del_kubernetes_master

- name: "卸载kubernetes client"
  gather_facts: no
  hosts: client
  roles:
  - del_kubernetes_client
  tags:
  - del_kubernetes_client

- name: "卸载kubernetes node"
  gather_facts: no
  hosts: node
  roles:
  - del_kubernetes_node
  tags:
  - del_kubernetes_node