- name: "删除res临时目录"
  hosts: deploy
  gather_facts: no
  roles:
  - del_res_tmp
  tags:
  - del_res_tmp

- name: "删除证书"
  hosts: all
  gather_facts: no
  roles:
  - del_certificate
  tags:
  - del_certificate