#- name: "删除res临时目录"
#  hosts: all
#  roles:
#  - del_res_tmp
#  tags:
#  - del_res_tmp

- name: "删除cfssl相关工具"
  hosts: all
  roles:
  - del_cfssl
  tags:
  - del_cfssl

- name: "删除cfssl相关工具"
  hosts: all
  roles:
  - del_cert
  tags:
  - del_cert


- name: "卸载etcd"
  hosts: etcd
  roles:
  - del_etcd
  tags:
  - del_etcd