- name: 创建TLS临时目录
  file:
    path: "{{tmp_tls_dir}}"
    state: directory

- name: 创建 ca-config.json
  template:
    src: ca-config.json.j2
    dest: "{{tmp_tls_dir}}/ca-config.json"

- name: 创建 ca-config.json
  template:
    src: ca-csr.json.j2
    dest: "{{tmp_tls_dir}}/ca-csr.json"

- name: 生成ca证书
  shell: cfssl gencert -initca ca-csr.json | cfssljson -bare ca
  args:
    chdir: "{{tmp_tls_dir}}"

- name: 分发ca证书
  become: true
  copy:
    src: "{{tmp_tls_dir}}/{{item}}"
    dest: "{{tmp_tls_dir}}"
  with_items:
  - ca-key.pem
  - ca.pem