- name: 检测etcd服务文件是否存在
  stat:
    path: /etc/systemd/system/etcd.service
  register: etcd

- name: 停止etcd服务
  systemd:
    state: stopped
    enabled: no
    name: etcd
  when: etcd.stat.exists == true

- name: 删除etcd服务文件
  become: true
  file:
    path: /etc/systemd/system/etcd.service
    state: absent

- name: 删除etcd相关目录
  become: true
  file:
    path: /var/lib/etcd
    state: absent