- name: 创建TLS临时目录
  file:
    path: "{{tmp_tls_dir}}"
    state: directory

- name: 创建 admin-csr.json
  template:
    src: admin-csr.json.j2
    dest: "{{tmp_tls_dir}}/admin-csr.json"

- name: 生成admin证书
  shell: "cfssl gencert -ca={{tmp_tls_dir}}/ca.pem \
                     -ca-key={{tmp_tls_dir}}/ca-key.pem \
                     -config={{tmp_tls_dir}}/ca-config.json \
                     -profile=kubernetes admin-csr.json | cfssljson -bare admin"
  args:
    chdir: "{{tmp_tls_dir}}"