- name: 创建 flanneld-csr.json
  template:
    src: flanneld-csr.json.j2
    dest: "{{tmp_tls_dir}}/flanneld-csr.json"

- name: 生成flanneld证书
  shell: "cfssl gencert -ca={{tmp_tls_dir}}/ca.pem \
                     -ca-key={{tmp_tls_dir}}/ca-key.pem \
                     -config={{tmp_tls_dir}}/ca-config.json \
                     -profile=kubernetes flanneld-csr.json | cfssljson -bare flanneld"
  args:
    chdir: "{{tmp_tls_dir}}"