- name: 创建TLS临时目录
  file:
    path: "{{tmp_tls_dir}}"
    state: directory

- name: 创建 kubernetes-csr.json
  template:
    src: kubernetes-csr.json.j2
    dest: "{{tmp_tls_dir}}/kubernetes-csr.json"

- name: 生成kubernetes证书
  shell: "cfssl gencert -ca={{tmp_tls_dir}}/ca.pem \
                     -ca-key={{tmp_tls_dir}}/ca-key.pem \
                     -config={{tmp_tls_dir}}/ca-config.json \
                     -profile=kubernetes kubernetes-csr.json | cfssljson -bare kubernetes"
  args:
    chdir: "{{tmp_tls_dir}}"